name: Release

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
    
    - name: Build release
      run: cargo build --release --verbose
    
    - name: Create release archive
      run: |
        mkdir -p release
        cp target/release/coomerd release/
        tar czf coomerd-linux-x86_64.tar.gz -C release .
    
    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./coomerd-linux-x86_64.tar.gz
        asset_name: coomerd-linux-x86_64.tar.gz
        asset_content_type: application/gzip 